services:
  app:
    build: .
    container_name: mec_checker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./available.json:/app/available.json
      - ./storage_state.json:/app/storage_state.json
