#!/bin/bash
set -e

# entrypoint.sh - exports .env variables for cron and starts cron
# If CRON_DISABLED=true then runs the command once in foreground (useful for debugging)

ENV_FILE="/app/.env"
ENV_CRON_FILE="/etc/envcron"
LOG_FILE="/var/log/mec_cupos_checker.log"
PYTHON_PATH=$(which python || which python3)
CRON_JOB="*/${CRON_JOB_TIMER_MINUTES} * * * * . ${ENV_CRON_FILE} && cd /app && ${PYTHON_PATH} main.py >> ${LOG_FILE} 2>&1"

# Function to create log file and directories
create_log_file() {
  mkdir -p /var/log
  touch ${LOG_FILE}
  chmod 666 ${LOG_FILE}
  echo "=== Log file created at $(date) ===" >> ${LOG_FILE}
}

# Function to export variables for cron
setup_env_for_cron() {
  echo "# Variables exported for cron (generated by entrypoint.sh)" > ${ENV_CRON_FILE}
  echo "# Generated at $(date)" >> ${ENV_CRON_FILE}

  # Add PATH to ensure Python and other commands are found
  echo "export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin" >> ${ENV_CRON_FILE}

  if [ -f "${ENV_FILE}" ]; then
    echo "Loading environment from ${ENV_FILE}"
    # Filter valid lines and don't export comments
    grep -v '^#' ${ENV_FILE} | grep -E '.+=.+' | sed "s/^[ \t]*//" | while IFS= read -r line; do
      key=$(printf "%s" "$line" | sed -E "s/=.*//")
      value=$(printf "%s" "$line" | sed -E "s/^[^=]*=//")
      # Escape backslashes and double quotes, then write with double quotes
      value_escaped=$(printf "%s" "$value" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
      echo "export ${key}=\"${value_escaped}\"" >> ${ENV_CRON_FILE}
    done
  else
    echo "No .env file found, using container environment variables"
    # No .env copied in the image; dump current environment variables
    # Exclude typical system variables to avoid noise
    env | while IFS='=' read -r key value; do
      case "$key" in
        PWD|OLDPWD|HOME|SHLVL|PATH|TERM|HOSTNAME|LANG|LANGUAGE|LC_*)
          continue
          ;;
      esac
      # escape backslashes and double quotes
      value_escaped=$(printf "%s" "$value" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
      echo "export ${key}=\"${value_escaped}\"" >> ${ENV_CRON_FILE}
    done
  fi
  chmod 644 ${ENV_CRON_FILE}
  echo "Environment file created at ${ENV_CRON_FILE}"
}

# Function to run the project once
run_once() {
  echo "Running project once: ${PYTHON_PATH} main.py"
  . ${ENV_CRON_FILE} || true
  cd /app
  ${PYTHON_PATH} main.py
  echo "Single execution completed with exit code: $?"
}

# Function to setup the cron job
setup_cron() {
  CRON_TMP_FILE="/tmp/mec_cron"
  echo "${CRON_JOB}" > ${CRON_TMP_FILE}
  crontab ${CRON_TMP_FILE}
  echo "Crontab installed at $(date):"
  crontab -l
}

# Function to start the cron daemon
start_cron() {
  echo "=== Starting cron daemon at $(date) ===" | tee -a ${LOG_FILE}
  echo "Cron job schedule: ${CRON_JOB}" | tee -a ${LOG_FILE}

  if command -v cron >/dev/null 2>&1; then
    echo "Starting cron in foreground..." | tee -a ${LOG_FILE}
    cron -f
  elif command -v crond >/dev/null 2>&1; then
    echo "Starting crond in foreground..." | tee -a ${LOG_FILE}
    crond -f
  else
    echo "ERROR: No cron daemon found" | tee -a ${LOG_FILE}
    exit 1
  fi
}

# Main execution
echo "=== Entrypoint started at $(date) ==="

create_log_file
setup_env_for_cron

# If CRON_DISABLED=true, run only once and exit
if [ "${CRON_DISABLED}" = "true" ] || [ "${CRON_DISABLED}" = "1" ]; then
  echo "CRON_DISABLED is set, running once and exiting..."
  run_once
  exit $?
fi

# Setup and start cron
setup_cron
run_once
start_cron
